export default {
  INPUT_ANDROID_UNDERLINE: '#eeeeee',
  INPUT_ANDROID_UNDERLINE_FOCUSED: '#CCC',
  title: '#333',
  minimum_text: '#999',
  label: '#999',
  button: '#2E5878',
  backButton: '#2E5878',
  buttonText: '#FFF',
  placeholderTextColor: '#DDD',
  errorColor: 'red',
  buttonLoading: '#DDD',
  tabBarIcon: '#B2B2B2',
  tabBarText: '#B2B2B2',
  tabBarIconActive: '#c43638',
  tabBarTextActive: '#c43638',
  darkText: '#434343',
  primary: '#c43638',
  secondary: '#FFFFFF',
  terciary: '#F6F6F6',
  quaternary: '#B2B2B2',
};
